# Data configs
dataset: "ycbv"
obj_id: "000001"
diameter: 172.063
project_dir: "/home/kimbo/bop_challenge"
dataset_dir: "/home/jim/Core7/${dataset}"

# PPF configs
voxel_size: 1.72063  # tau = 0.01
num_patches: 128
num_pts_per_patch: 2048

# CUDA configs
debug: True
seed: 309805
device: "cuda:0"

# Training
train:
  num_epochs: 100
  scheduler_interval: 5
  checkpoint_epoch: 10
  checkpoint_path: "${project_dir}/checkpoints/ckpt_${dataset}_obj${obj_id}.pth"
  device: ${device}

# Model
model:
  class: model.AutoEncoder
  params:
    num_pts_per_patch: ${num_pts_per_patch}
    device: ${device}
optimizer: 
  lr: 3e-4
  weight_decay: 1e-6
scheduler_gamma: 0.5

# Data loader configs
dl:
  batch_size: 1
  num_workers: 8
  shuffle: True

# Dataset configs
num_train_images: 2000
num_val_images: 500

train_ds:
  class: dataset.PPFDataset
  params: 
    ppf_dir: "${project_dir}/ppf_data/train"
    num_images: ${num_train_images}

val_ds:
  class: dataset.PPFDataset
  params: 
    ppf_dir: "${project_dir}/ppf_data/test"
    num_images: ${num_val_images}

# Point cloud dataset
model_file: "${dataset_dir}/models/obj_${obj_id}.ply"

train_pcd_ds:
  class: dataset.PointCloudDataset
  params:
    image_dir: "${project_dir}/pcd_data/train/obj_${obj_id}"
    num_images: ${num_train_images}
    model_file: ${model_file}
    voxel_size: ${voxel_size}
    num_patches: ${num_patches}
    num_pts_per_patch: ${num_pts_per_patch}
    device: ${device}

val_pcd_ds:
  class: dataset.PointCloudDataset
  params:
    image_dir: "${project_dir}/pcd_data/test/obj_${obj_id}"
    num_images: ${num_val_images}
    model_file: ${model_file}
    voxel_size: ${voxel_size}
    num_patches: ${num_patches}
    num_pts_per_patch: ${num_pts_per_patch}
    device: ${device}
